---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Geheimzinnige brief
description: Maak een geheimzinnige brief met veel verschillende stijlen.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2025-01-02
steps:
  - 
    title: Inleiding
  - 
    title: Kies je bericht
    completion:
      - engaged
  - 
    title: Je bericht bewerken
  - 
    title: Class stijlen gebruiken
  - 
    title: 'Uitdaging: maak je bericht op'
    completion:
      - internal
      - external
  - 
    title: Klasse bewerken
    challenge: true
