---
hero_image: images / banner.png
theme: gul
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programmering-0, phys-comp-0, produksjon-0, fellesskap-0
title: Mystery Letter
description: Lag et mysterium brev med mange forskjellige stiler.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: Kunst
technologies: html-css-javascript
site_areas: prosjekter
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2025-01-02
steps:
  - 
    title: What you will make
  - 
    title: Edit the message
    completion:
      - engaged
  - 
    title: Add class styles
  - 
    title: Editing Classes
  - 
    title: Create a new class
    completion:
      - internal
      - external
  - 
    title: Challenge
    challenge: true
