---
hero_image: images/banner.png
theme: amarelo
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programação-0, phys-comp-0, fabricação-0, comunidade-0
title: Carta Mistério
description: Cria uma carta mistério com vários estilos diferentes.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: arte
technologies: html-css-javascript
site_areas: projetos
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2025-01-02
steps:
  - 
    title: What you will make
  - 
    title: Edit the message
    completion:
      - engaged
  - 
    title: Add class styles
  - 
    title: Editing Classes
  - 
    title: Create a new class
    completion:
      - internal
      - external
  - 
    title: Challenge
    challenge: true
