---
hero_image: images/banner.png
theme: amarelo
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Carta Mistério
description: Cria uma carta mistério com vários estilos diferentes.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: Escolhe a Tua Mensagem
  - 
    title: Edita a Tua Mensagem
  - 
    title: Usando Estilos de Classes
  - 
    title: 'Desafio: Estiliza a Tua Mensagem'
  - 
    title: Editando as Classes
  - 
    title: Cria uma Nova Classe
  - 
    title: 'Desafio: Cria um Estilo de impressão de computador'
  - 
    title: 'Desafio: Cria os Teus Próprios Estilos'
