---
hero_image: images/banner.png
theme: žuta
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Zagonetno pismo
description: U ovom projektu napravit ćeš zagonetno pismo koje izgleda kao da je svako slovo izrezano iz različitih novina, magazina, stripa ili nekog drugog izvora.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: art
technologies: html-css-javascript
site_areas: projekti
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Sretan rođendan
  - 
    title: Choose Your Message
  - 
    title: Editing Your Message
  - 
    title: Using Class Styles
  - 
    title: 'Challenge: Style Your Message'
  - 
    title: Editing Classes
  - 
    title: Create a New Class
  - 
    title: 'Challenge: Create A Computer Printout Style'
  - 
    title: 'Challenge: Create Your Own Styles'
