---
hero_image: images / banner.png
theme: رنگ زرد
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1، design-1، programming-0، phys-comp-0، manufacture-0، community-0
title: نامه اسرار آمیز
description: یک نامه رمز و راز با تعداد زیادی از سبک های مختلف ایجاد کنید.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: هنر
technologies: html-css-javascript
site_areas: پروژه ها
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2025-01-02
steps:
  - 
    title: What you will make
  - 
    title: Edit the message
    completion:
      - engaged
  - 
    title: Add class styles
  - 
    title: Editing Classes
  - 
    title: Create a new class
    completion:
      - internal
      - external
  - 
    title: Challenge
    challenge: true
