---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Geheimnisvoller Brief
description: Produziere einen geheimnisvollen Brief mit ganz vielen, verschiedenen Stilen.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: ''
technologies: html/css
site_areas: codeclub, webdev
steps:
- title: Einführung
- title: Wähle deine Mitteilung aus
- title: Bearbeite deine Botschaft
- title: Nutzung der Klassenstile
- title: 'Aufgabe: Gestalte deinen Botschaftsstil'
- title: Klassen bearbeiten
- title: Eine neue Klasse erzeugen
- title: 'Aufgabe: Erstelle einen Stil, der wie vom Computer ausgedruckt aussieht'
- title: 'Aufgabe: Erstelle deinen eigenen Stil'

