---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Geheimnisvoller Brief
description: Erstelle einen geheimnisvollen Brief mit ganz vielen, verschiedenen Stilen.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Wähle deine Nachricht
  - 
    title: Bearbeite deine Nachricht
  - 
    title: Verwende Klassenstile
  - 
    title: 'Herausforderung: Gestalte deine Nachricht'
  - 
    title: Klassen bearbeiten
  - 
    title: Eine neue Klasse erzeugen
  - 
    title: 'Herausforderung: Erstelle einen Stil, der wie vom Computer ausgedruckt aussieht'
  - 
    title: 'Herausforderung: Erstelle deinen eigenen Stil'
