---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Geheimnisvoller Brief
description: Produziere einen geheimnisvollen Brief mit ganz vielen, verschiedenen Stilen.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einführung
  - 
    title: Wähle deine Mitteilung aus
  - 
    title: Bearbeite deine Botschaft
  - 
    title: Nutzung der Klassenstile
  - 
    title: 'Aufgabe: Gestalte deinen Botschaftsstil'
  - 
    title: Klassen bearbeiten
  - 
    title: Eine neue Klasse erzeugen
  - 
    title: 'Aufgabe: Erstelle einen Stil, der wie vom Computer ausgedruckt aussieht'
  - 
    title: 'Aufgabe: Erstelle deinen eigenen Stil'
