---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Scrisoare misterioasă
description: Creează o scrisoare misterioasă cu o mulțime de stiluri.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2017-01-01
steps:
  - 
    title: Introducere
  - 
    title: Alegerea mesajului tău
  - 
    title: Editarea mesajului tău
  - 
    title: Folosirea claselor de stiluri
  - 
    title: 'Provocare: stilizează-ți mesajul'
  - 
    title: Editarea claselor
  - 
    title: Crearea unei noi clase
  - 
    title: 'Provocare: creează un șablon de printare'
  - 
    title: 'Provocare: creează-ți propriile stiluri'
