---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Carta Misteriosa
description: Crie uma carta misteriosa com muitos estilos diferentes.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2025-01-02
steps:
  - 
    title: Introdução
  - 
    title: Escolha sua mensagem
    completion:
      - engaged
  - 
    title: Editando sua mensagem
  - 
    title: Usando classes de Estilos
  - 
    title: 'Desafio: Estilize sua mensagem'
    completion:
      - internal
      - external
  - 
    title: Editando suas classes
    challenge: true
