---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Carta Misteriosa
description: Crie uma carta misteriosa com muitos estilos diferentes.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Introdução
- title: Escolha sua mensagem
- title: Editando sua mensagem
  completion:
  - engaged
- title: Usando classes de Estilos
- title: 'Desafio: Estilize sua mensagem'
- title: Editando suas classes
- title: Criando uma nova classe
  completion:
  - internal
- title: 'Desafio: Criando um estilo de impressão de computador'
- title: 'Desafio: Criando seus próprios estilos'
