---
hero_image: images / banner.png
theme: kuning
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, desain-1, pemrograman-0, phys-comp-0, manufacture-0, community-0
title: Surat Misteri
description: Buat surat misteri dengan banyak gaya yang berbeda.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: seni
technologies: html-css-javascript
site_areas: proyek
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2017-01-01
steps:
  - 
    title: pengantar
  - 
    title: Pilih Pesan Anda
  - 
    title: Mengedit Pesan Anda
  - 
    title: Menggunakan Gaya Kelas
  - 
    title: 'Tantangan: Gaya Pesan Anda'
  - 
    title: Kelas Editing
  - 
    title: Buat Kelas Baru
  - 
    title: 'Tantangan: Buat Gaya Cetak Komputer'
  - 
    title: 'Tantangan: Buat Gaya Anda Sendiri'
