---
hero_image: images / banner.png
theme: sárga
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Rejtély levél
description: Készítsen rejtélyt tartalmazó levelet, sok különböző stílusban.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2017-01-01
steps:
  - 
    title: Bevezetés
  - 
    title: Válassza ki az üzenetet
  - 
    title: Az üzenet szerkesztése
  - 
    title: Osztálystílusok használata
  - 
    title: 'Kihívás: stílusosítsa az üzenetet'
  - 
    title: Osztályok szerkesztése
  - 
    title: Hozzon létre egy új osztályt
  - 
    title: 'Kihívás: hozzon létre egy számítógépes nyomtatási stílust'
  - 
    title: 'Kihívás: Készítse el saját stílusát'
