---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Carta Misteriosa
description: Crea una carta misteriosa con muchos estilos diferentes.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: arte
technologies: html-css-javascript
site_areas: proyectos
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2025-01-02
steps:
  - 
    title: Introducción
  - 
    title: Elige tu mensaje
    completion:
      - engaged
  - 
    title: Editando tu mensaje
  - 
    title: Usando clases de estilo
  - 
    title: 'Reto: dale estilo a tu mensaje'
    completion:
      - internal
      - external
  - 
    title: Editando clases
    challenge: true
