---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Salakiri
description: Loo paljude erinevate stiilidega salakiri.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2025-01-02
steps:
  - 
    title: Sissejuhatus
  - 
    title: Vali oma s천num
    completion:
      - engaged
  - 
    title: Oma s천numi muutmine
  - 
    title: Klassistiilide kasutamine
  - 
    title: 'V채ljakutse: kujunda oma s천numit'
    completion:
      - internal
      - external
  - 
    title: Klasside muutmine
    challenge: true
