---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Tajemniczy list
description: Naucz się, jak stworzyć list z każdym słowem w innym stylu.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Wybierz swoją wiadomość
  - 
    title: Edytowanie Twojej wiadomości
  - 
    title: Użycie stylów klas
  - 
    title: 'Wyzwanie: Stylizuj swoją wiadomość'
  - 
    title: Edytowanie klas
  - 
    title: Tworzenie nowej klasy
  - 
    title: 'Wyzwanie: Utwórz styl wydruku komputerowego'
  - 
    title: 'Wyzwanie: Utwórz swój własny styl'
