---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Tajemniczy list
description: Stwórz tajemniczy list z wieloma różnymi stylami.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2025-01-02
steps:
  - 
    title: Wprowadzenie
  - 
    title: Wybierz swoją wiadomość
    completion:
      - engaged
  - 
    title: Edytowanie Twojej wiadomości
  - 
    title: Użycie stylów klas
  - 
    title: 'Wyzwanie: Wystylizuj swoją wiadomość'
    completion:
      - internal
      - external
  - 
    title: Edytowanie klas
    challenge: true
