---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Zagonetno pismo
description: Napravi zagonetno pismo sa više različitih stilova.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2017-01-01
steps:
- title: Uvod
- title: Odaberi svoju poruku
- title: Uređivanje poruke
  completion:
  - engaged
- title: Upotreba stilova klase
- title: 'Izazov: Stilizuj svoju poruku'
- title: Uređivanje klasa
- title: Kreiraj novu klasu
  completion:
  - internal
- title: 'Izazov: Kreiraj stil dokumenta odštampanog sa računara'
- title: 'Izazov: Kreiraj sopstvene stilove'
