---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Lettre Mystère
description: Créer une lettre mystérieuse avec plein de styles différents.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: ''
technologies: html/css
site_areas: codeclub, webdev
steps:
- title: Introduction
- title: Choisi ton message
- title: Édite ton message
- title: Utilisation des classes CSS
- title: 'Défi: Style ton message'
- title: Édite tes classes
- title: Créer une nouvelle classe
- title: "Défi:  Créer un style écran d'ordinateur"
- title: 'Défi: Créer ton prore style'

