---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Lettera misteriosa
description: Crea una lettera misteriosa con tanti stili diversi.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2025-01-02
steps:
  - 
    title: Introduzione
  - 
    title: Scegli il messaggio
    completion:
      - engaged
  - 
    title: Modifica del messaggio
  - 
    title: Utilizzo degli stili di classe
  - 
    title: 'Sfida: Attribuisci uno stile al messaggio'
    completion:
      - internal
      - external
  - 
    title: Modifica delle classi
    challenge: true
