---
hero_image: images/banner.png
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Gizemli Mektup
description: Birçok farklı stil içeren gizemli bir mektup oluşturun.
original_url: https://codeclubprojects.org/en-GB/webdev/mystery-letter
interests: art
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3.1
last_tested: 2017-01-01
steps:
- title: Giriş
- title: Mesajınızı Seçin
- title: Mesajınızı Düzenleyin
  completion:
  - engaged
- title: Sınıf Stillerini Kullanma
- title: 'Meydan Okuma: Mesajını Stillendir'
- title: Sınıfları Düzenleme
- title: Yeni Bir Sınıf Oluştur
  completion:
  - internal
- title: 'Meydan Okuma: Bir Bilgisayar Çıktısı Stili Oluştur'